return {
	DEBUG_MODE = true,
	ValidActions = { "Stab", "Throw" },
	MaxDirectionMagnitude = 1.1,
	StabCooldown = 0.5,
	ThrowCooldown = 0.5,
	StabAnimationId = "",
	ThrowAnimationId = "",
	StabDuration = 0.5,
	ThrowDuration = 0.5,
	StabDamage = 25,
	ThrowDamage = 40,
	ThrowSpeed = 100,
	StuckDespawnTime = 5,
	ProjectileMaxLifetime = 7,
}
